require('config.colorscheme')
-- require('config.completion')
require('config.compe')
require('config.fugitive')

require('config.comment')
require('config.nvimtree')
require('config.treesitter')
require('config.vim_rooter')
require('config.galaxyline')
require('config.telescope')
require('config.hop')
require('config.dashboard')
require('config.nvim-lightbulb')
require('config.lspsaga')
require('config.lsp')
-- require('config.lspinstall')
