require('config.colorscheme')
require('config.cmp')
require('config.neogit')
require('config.comment')
require('config.nvimtree')
require('config.treesitter')
-- require('config.vim_rooter')
require('config.project')
require('config.lualine')
require('config.barbar')
require('config.telescope')
require('config.hop')
require('config.dashboard')
require('config.nvim-spectre')
require('config.neoclip')
require('config.toggleterm')
require('config.autopairs')
