require('config.colorscheme')
require('config.compe')
-- require('config.fugitive')
require('config.neogit')
require('config.comment')
require('config.nvimtree')
require('config.treesitter')
require('config.vim_rooter')
require('config.galaxyline')
require('config.barbar')
require('config.telescope')
require('config.hop')
require('config.dashboard')
require('config.nvim-spectre')
require('config.nvim-lightbulb')
require('config.lspsaga')
require('config.lsp')
-- require('config.lspinstall')
